
export const ADD_TRAVELS_START = 'ADD_TRAVELS_START';
export const ADD_TRAVELS_SUCCESS = 'ADD_TRAVELS_SUCCESS';
export const ADD_TRAVELS_FAIL = 'ADD_TRAVELS_FAIL';
export const ADD_TRAVELS_INIT = 'ADD_TRAVELS_INIT';


export const FETCH_TRAVELS_START = 'FETCH_TRAVELS_START';
export const FETCH_TRAVELS_SUCCESS = 'FETCH_TRAVELS_SUCCESS';
export const FETCH_TRAVELS_FAIL = 'FETCH_TRAVELS_FAIL';

export const DELETE_TRAVELS_START = 'DELETE_TRAVELS_START';
export const DELETE_TRAVELS_SUCCESS = 'DELETE_TRAVELS_SUCCESS';
export const DELETE_TRAVELS_FAIL = 'DELETE_TRAVELS_FAIL';